# Generated by Django 6.0.6 on 2026-06-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('biometric_id', models.CharField(blank=True, help_text='Hikvision Device EmployeeNo / Card Number', max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERPAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('serial_no', models.IntegerField(unique=True)),
                ('verify_mode', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.employee')),
            ],
        ),
    ]
