# Generated by Django 6.0.6 on 2026-06-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('gender', models.CharField(blank=True, default='Unknown', max_length=20)),
                ('user_type', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('num_fp', models.IntegerField(default=0)),
                ('num_face', models.IntegerField(default=0)),
                ('group_id', models.CharField(blank=True, default='', max_length=50)),
                ('face_url', models.CharField(blank=True, default='', max_length=500)),
                ('last_punch_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PunchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(unique=True)),
                ('employee_id_str', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('time', models.DateTimeField()),
                ('verify_mode', models.CharField(blank=True, default='', max_length=100)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='monitor.employee')),
            ],
        ),
    ]
