# Generated by Django 6.0.6 on 2026-06-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchevent',
            name='shared_to_erp',
            field=models.BooleanField(default=False),
        ),
    ]
