# Generated by Django 6.0.6 on 2026-07-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_punchevent_shared_to_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchevent',
            name='erp_send_failed',
            field=models.BooleanField(default=False),
        ),
    ]
